# Generated by Django 3.1.2 on 2020-10-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('image_url', models.TextField()),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('videoURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('shirt_type', models.CharField(max_length=30)),
                ('shirt_image', models.CharField(max_length=100)),
                ('original_image', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Atrocity', models.ManyToManyField(blank=True, related_name='Shirt', to='Alt.Atrocity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.country')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('year_started', models.IntegerField()),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('website_url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.CharField(max_length=100)),
                ('atrocity', models.ManyToManyField(blank=True, null=True, related_name='NonProfit', to='Alt.Atrocity')),
                ('category', models.ManyToManyField(related_name='NonProfit', to='Alt.Category')),
                ('shirtList', models.ManyToManyField(related_name='NonProfit', to='Alt.Shirt')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='nonProfitList',
            field=models.ManyToManyField(blank=True, related_name='Category', to='Alt.NonProfit'),
        ),
        migrations.AddField(
            model_name='category',
            name='shirtList',
            field=models.ManyToManyField(blank=True, related_name='Category', to='Alt.Shirt'),
        ),
        migrations.AddField(
            model_name='atrocity',
            name='category',
            field=models.ManyToManyField(related_name='Atrocity', to='Alt.Category'),
        ),
        migrations.AddField(
            model_name='atrocity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.country'),
        ),
    ]
