# Generated by Django 3.1.5 on 2021-01-08 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('image_url', models.TextField()),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('videoURL', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('year_started', models.IntegerField()),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('website_url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('shirt_type', models.CharField(max_length=30)),
                ('shirt_image', models.CharField(max_length=100)),
                ('original_image', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Atrocity', models.ManyToManyField(blank=True, related_name='Shirt', to='Alt.Atrocity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.country')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.shirt')),
            ],
        ),
    ]
