# Generated by Django 3.2.3 on 2021-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0003_auto_20210517_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='main_image',
            field=models.CharField(max_length=200),
        ),
    ]
