# Generated by Django 3.1.2 on 2020-10-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='atrocity_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to='Alt.atrocity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nonProfit_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to='Alt.nonprofit'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfiles', to='Alt.shirt', verbose_name='shirts'),
        ),
    ]
