# Generated by Django 3.1.5 on 2021-01-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210108_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRcode',
        ),
    ]
