# Generated by Django 3.1.2 on 2020-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201015_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
