# Generated by Django 3.1.2 on 2020-10-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0001_initial'),
        ('api', '0003_userprofile_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='atrocity_list',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='atrocity_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserProfiles', to='Alt.Atrocity'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nonProfit_list',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nonProfit_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserProfiles', to='Alt.NonProfit'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shirt_list',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserProfiles', to='Alt.Shirt', verbose_name='shirts'),
        ),
    ]
