# Generated by Django 3.1.2 on 2020-10-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0001_initial'),
        ('api', '0004_auto_20201015_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='atrocity_list',
            field=models.ManyToManyField(blank=True, related_name='UserProfiles', to='Alt.Atrocity'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nonProfit_list',
            field=models.ManyToManyField(blank=True, related_name='UserProfiles', to='Alt.NonProfit'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shirt_list',
            field=models.ManyToManyField(blank=True, related_name='UserProfiles', to='Alt.Shirt', verbose_name='shirts'),
        ),
    ]
