# Generated by Django 3.2.3 on 2021-06-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210604_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_created',
            field=models.BooleanField(default=False),
        ),
    ]
