# Generated by Django 3.1.5 on 2021-01-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210120_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='johnny', max_length=100),
            preserve_default=False,
        ),
    ]
