# Generated by Django 3.1.5 on 2021-01-21 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210121_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='altrue_name',
        ),
    ]
