# Generated by Django 3.1.5 on 2021-01-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_userprofile_altrue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='altrue_name',
            field=models.CharField(default='jaja', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
