# Generated by Django 3.1.5 on 2021-01-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210121_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='altrue_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
